"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let name = "Alice";
let age = 30;
let isStudent = true;
let city = "New York";
let grade = 80;
let country = "Canada";
console.log("Is name equal to 'Alice'? I predict True.");
console.log(name == "Alice");
console.log("Is age greater than or equal to 18? I predict True.");
console.log(age >= 18);
console.log("Is isStudent true? I predict True.");
console.log(isStudent);
console.log("Is city not equal to 'London'? I predict True.");
console.log(city != "London");
console.log("Is grade greater than 75? I predict True.");
console.log(grade > 75);
console.log("Is age less than 21? I predict False.");
console.log(age < 21);
console.log("Is country equal to 'USA'? I predict False.");
console.log(country == "USA");
console.log("Is name not equal to 'Alice'? I predict False.");
console.log(name != "Alice");
console.log("Is isStudent false? I predict False.");
console.log(!isStudent);
console.log("Is age equal to '30'? I predict False.");
console.log(age == 30);
